# This file is auto-generated. Do not modify manually.
# coding: utf-8

# flake8: noqa
"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from payrisk_v1.models.account import Account
from payrisk_v1.models.account_check_request import AccountCheckRequest
from payrisk_v1.models.avs_result_enum import AvsResultEnum
from payrisk_v1.models.bank_transfer import BankTransfer
from payrisk_v1.models.card import Card
from payrisk_v1.models.card_network_enum import CardNetworkEnum
from payrisk_v1.models.category_signal import CategorySignal
from payrisk_v1.models.channel_enum import ChannelEnum
from payrisk_v1.models.check_request import CheckRequest
from payrisk_v1.models.confidence_enum import ConfidenceEnum
from payrisk_v1.models.crypto import Crypto
from payrisk_v1.models.cvv_result_enum import CvvResultEnum
from payrisk_v1.models.decision_response import DecisionResponse
from payrisk_v1.models.device_info import DeviceInfo
from payrisk_v1.models.discount_code import DiscountCode
from payrisk_v1.models.entity_ids import EntityIds
from payrisk_v1.models.entry_method_enum import EntryMethodEnum
from payrisk_v1.models.external_assessment import ExternalAssessment
from payrisk_v1.models.fraud_score import FraudScore
from payrisk_v1.models.identity import Identity
from payrisk_v1.models.integrity import Integrity
from payrisk_v1.models.interaction import Interaction
from payrisk_v1.models.interaction_type_enum import InteractionTypeEnum
from payrisk_v1.models.invoice import Invoice
from payrisk_v1.models.ip_info import IpInfo
from payrisk_v1.models.kyc_check_request import KycCheckRequest
from payrisk_v1.models.kyc_payload import KycPayload
from payrisk_v1.models.merchant_context import MerchantContext
from payrisk_v1.models.order_context import OrderContext
from payrisk_v1.models.payer_type_enum import PayerTypeEnum
from payrisk_v1.models.payment_authorization_outcome import \
    PaymentAuthorizationOutcome
from payrisk_v1.models.payment_capture_outcome import PaymentCaptureOutcome
from payrisk_v1.models.payment_card_type_enum import PaymentCardTypeEnum
from payrisk_v1.models.payment_chargeback import PaymentChargeback
from payrisk_v1.models.payment_chargeback_outcome import \
    PaymentChargebackOutcome
from payrisk_v1.models.payment_dispute_outcome import PaymentDisputeOutcome
from payrisk_v1.models.payment_event import PaymentEvent
from payrisk_v1.models.payment_event_type import PaymentEventType
from payrisk_v1.models.payment_method import PaymentMethod
from payrisk_v1.models.payment_outcome import PaymentOutcome
from payrisk_v1.models.payment_realtime_type_enum import \
    PaymentRealtimeTypeEnum
from payrisk_v1.models.payment_refund_outcome import PaymentRefundOutcome
from payrisk_v1.models.payment_wallet_type_enum import PaymentWalletTypeEnum
from payrisk_v1.models.postal_address import PostalAddress
from payrisk_v1.models.problem import Problem
from payrisk_v1.models.purchase import Purchase
from payrisk_v1.models.purchase_initiator_enum import PurchaseInitiatorEnum
from payrisk_v1.models.purchase_sequence_enum import PurchaseSequenceEnum
from payrisk_v1.models.purchase_usage_enum import PurchaseUsageEnum
from payrisk_v1.models.realtime import Realtime
from payrisk_v1.models.reason_detail import ReasonDetail
from payrisk_v1.models.risk_breakdown import RiskBreakdown
from payrisk_v1.models.risk_category_enum import RiskCategoryEnum
from payrisk_v1.models.risk_level_enum import RiskLevelEnum
from payrisk_v1.models.sca_method_enum import ScaMethodEnum
from payrisk_v1.models.score_record import ScoreRecord
from payrisk_v1.models.scores_success_response import ScoresSuccessResponse
from payrisk_v1.models.signals_account_variant import SignalsAccountVariant
from payrisk_v1.models.signals_interaction_variant import \
    SignalsInteractionVariant
from payrisk_v1.models.signals_request import SignalsRequest
from payrisk_v1.models.stored_credential_context import StoredCredentialContext
from payrisk_v1.models.three_ds_data import ThreeDSData
from payrisk_v1.models.wallet import Wallet
