# coding: utf-8

# flake8: noqa
"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from alogram_payrisk._generated.payrisk_v1.models.account import Account
    from alogram_payrisk._generated.payrisk_v1.models.account_check_request import AccountCheckRequest
    from alogram_payrisk._generated.payrisk_v1.models.avs_result_enum import AvsResultEnum
    from alogram_payrisk._generated.payrisk_v1.models.bank_transfer import BankTransfer
    from alogram_payrisk._generated.payrisk_v1.models.card import Card
    from alogram_payrisk._generated.payrisk_v1.models.card_network_enum import CardNetworkEnum
    from alogram_payrisk._generated.payrisk_v1.models.category_signal import CategorySignal
    from alogram_payrisk._generated.payrisk_v1.models.channel_enum import ChannelEnum
    from alogram_payrisk._generated.payrisk_v1.models.check_request import CheckRequest
    from alogram_payrisk._generated.payrisk_v1.models.confidence_enum import ConfidenceEnum
    from alogram_payrisk._generated.payrisk_v1.models.crypto import Crypto
    from alogram_payrisk._generated.payrisk_v1.models.cvv_result_enum import CvvResultEnum
    from alogram_payrisk._generated.payrisk_v1.models.decision_response import DecisionResponse
    from alogram_payrisk._generated.payrisk_v1.models.device_info import DeviceInfo
    from alogram_payrisk._generated.payrisk_v1.models.entity_ids import EntityIds
    from alogram_payrisk._generated.payrisk_v1.models.entry_method_enum import EntryMethodEnum
    from alogram_payrisk._generated.payrisk_v1.models.fraud_score import FraudScore
    from alogram_payrisk._generated.payrisk_v1.models.identity import Identity
    from alogram_payrisk._generated.payrisk_v1.models.integrity import Integrity
    from alogram_payrisk._generated.payrisk_v1.models.interaction import Interaction
    from alogram_payrisk._generated.payrisk_v1.models.interaction_type_enum import InteractionTypeEnum
    from alogram_payrisk._generated.payrisk_v1.models.invoice import Invoice
    from alogram_payrisk._generated.payrisk_v1.models.ip_info import IpInfo
    from alogram_payrisk._generated.payrisk_v1.models.kyc_check_request import KycCheckRequest
    from alogram_payrisk._generated.payrisk_v1.models.kyc_payload import KycPayload
    from alogram_payrisk._generated.payrisk_v1.models.merchant_context import MerchantContext
    from alogram_payrisk._generated.payrisk_v1.models.order_context import OrderContext
    from alogram_payrisk._generated.payrisk_v1.models.payer_type_enum import PayerTypeEnum
    from alogram_payrisk._generated.payrisk_v1.models.payment_authorization_outcome import (
        PaymentAuthorizationOutcome,
    )
    from alogram_payrisk._generated.payrisk_v1.models.payment_capture_outcome import PaymentCaptureOutcome
    from alogram_payrisk._generated.payrisk_v1.models.payment_card_type_enum import PaymentCardTypeEnum
    from alogram_payrisk._generated.payrisk_v1.models.payment_chargeback import PaymentChargeback
    from alogram_payrisk._generated.payrisk_v1.models.payment_chargeback_outcome import PaymentChargebackOutcome
    from alogram_payrisk._generated.payrisk_v1.models.payment_dispute_outcome import PaymentDisputeOutcome
    from alogram_payrisk._generated.payrisk_v1.models.payment_event import PaymentEvent
    from alogram_payrisk._generated.payrisk_v1.models.payment_event_type import PaymentEventType
    from alogram_payrisk._generated.payrisk_v1.models.payment_method import PaymentMethod
    from alogram_payrisk._generated.payrisk_v1.models.payment_method_base import PaymentMethodBase
    from alogram_payrisk._generated.payrisk_v1.models.payment_outcome import PaymentOutcome
    from alogram_payrisk._generated.payrisk_v1.models.payment_realtime_type_enum import PaymentRealtimeTypeEnum
    from alogram_payrisk._generated.payrisk_v1.models.payment_refund_outcome import PaymentRefundOutcome
    from alogram_payrisk._generated.payrisk_v1.models.payment_wallet_type_enum import PaymentWalletTypeEnum
    from alogram_payrisk._generated.payrisk_v1.models.postal_address import PostalAddress
    from alogram_payrisk._generated.payrisk_v1.models.problem import Problem
    from alogram_payrisk._generated.payrisk_v1.models.purchase import Purchase
    from alogram_payrisk._generated.payrisk_v1.models.purchase_initiator_enum import PurchaseInitiatorEnum
    from alogram_payrisk._generated.payrisk_v1.models.purchase_sequence_enum import PurchaseSequenceEnum
    from alogram_payrisk._generated.payrisk_v1.models.purchase_usage_enum import PurchaseUsageEnum
    from alogram_payrisk._generated.payrisk_v1.models.realtime import Realtime
    from alogram_payrisk._generated.payrisk_v1.models.reason_detail import ReasonDetail
    from alogram_payrisk._generated.payrisk_v1.models.risk_breakdown import RiskBreakdown
    from alogram_payrisk._generated.payrisk_v1.models.risk_category_enum import RiskCategoryEnum
    from alogram_payrisk._generated.payrisk_v1.models.risk_level_enum import RiskLevelEnum
    from alogram_payrisk._generated.payrisk_v1.models.sca_method_enum import ScaMethodEnum
    from alogram_payrisk._generated.payrisk_v1.models.score_record import ScoreRecord
    from alogram_payrisk._generated.payrisk_v1.models.scores_success_response import ScoresSuccessResponse
    from alogram_payrisk._generated.payrisk_v1.models.signals_account_variant import SignalsAccountVariant
    from alogram_payrisk._generated.payrisk_v1.models.signals_interaction_variant import SignalsInteractionVariant
    from alogram_payrisk._generated.payrisk_v1.models.signals_request import SignalsRequest
    from alogram_payrisk._generated.payrisk_v1.models.stored_credential_context import StoredCredentialContext
    from alogram_payrisk._generated.payrisk_v1.models.three_ds_data import ThreeDSData
    from alogram_payrisk._generated.payrisk_v1.models.wallet import Wallet

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from alogram_payrisk._generated.payrisk_v1.models.account import Account
from alogram_payrisk._generated.payrisk_v1.models.account_check_request import AccountCheckRequest
from alogram_payrisk._generated.payrisk_v1.models.avs_result_enum import AvsResultEnum
from alogram_payrisk._generated.payrisk_v1.models.bank_transfer import BankTransfer
from alogram_payrisk._generated.payrisk_v1.models.card import Card
from alogram_payrisk._generated.payrisk_v1.models.card_network_enum import CardNetworkEnum
from alogram_payrisk._generated.payrisk_v1.models.category_signal import CategorySignal
from alogram_payrisk._generated.payrisk_v1.models.channel_enum import ChannelEnum
from alogram_payrisk._generated.payrisk_v1.models.check_request import CheckRequest
from alogram_payrisk._generated.payrisk_v1.models.confidence_enum import ConfidenceEnum
from alogram_payrisk._generated.payrisk_v1.models.crypto import Crypto
from alogram_payrisk._generated.payrisk_v1.models.cvv_result_enum import CvvResultEnum
from alogram_payrisk._generated.payrisk_v1.models.decision_response import DecisionResponse
from alogram_payrisk._generated.payrisk_v1.models.device_info import DeviceInfo
from alogram_payrisk._generated.payrisk_v1.models.entity_ids import EntityIds
from alogram_payrisk._generated.payrisk_v1.models.entry_method_enum import EntryMethodEnum
from alogram_payrisk._generated.payrisk_v1.models.fraud_score import FraudScore
from alogram_payrisk._generated.payrisk_v1.models.identity import Identity
from alogram_payrisk._generated.payrisk_v1.models.integrity import Integrity
from alogram_payrisk._generated.payrisk_v1.models.interaction import Interaction
from alogram_payrisk._generated.payrisk_v1.models.interaction_type_enum import InteractionTypeEnum
from alogram_payrisk._generated.payrisk_v1.models.invoice import Invoice
from alogram_payrisk._generated.payrisk_v1.models.ip_info import IpInfo
from alogram_payrisk._generated.payrisk_v1.models.kyc_check_request import KycCheckRequest
from alogram_payrisk._generated.payrisk_v1.models.kyc_payload import KycPayload
from alogram_payrisk._generated.payrisk_v1.models.merchant_context import MerchantContext
from alogram_payrisk._generated.payrisk_v1.models.order_context import OrderContext
from alogram_payrisk._generated.payrisk_v1.models.payer_type_enum import PayerTypeEnum
from alogram_payrisk._generated.payrisk_v1.models.payment_authorization_outcome import PaymentAuthorizationOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_capture_outcome import PaymentCaptureOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_card_type_enum import PaymentCardTypeEnum
from alogram_payrisk._generated.payrisk_v1.models.payment_chargeback import PaymentChargeback
from alogram_payrisk._generated.payrisk_v1.models.payment_chargeback_outcome import PaymentChargebackOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_dispute_outcome import PaymentDisputeOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_event import PaymentEvent
from alogram_payrisk._generated.payrisk_v1.models.payment_event_type import PaymentEventType
from alogram_payrisk._generated.payrisk_v1.models.payment_method import PaymentMethod
from alogram_payrisk._generated.payrisk_v1.models.payment_method_base import PaymentMethodBase
from alogram_payrisk._generated.payrisk_v1.models.payment_outcome import PaymentOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_realtime_type_enum import PaymentRealtimeTypeEnum
from alogram_payrisk._generated.payrisk_v1.models.payment_refund_outcome import PaymentRefundOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_wallet_type_enum import PaymentWalletTypeEnum
from alogram_payrisk._generated.payrisk_v1.models.postal_address import PostalAddress
from alogram_payrisk._generated.payrisk_v1.models.problem import Problem
from alogram_payrisk._generated.payrisk_v1.models.purchase import Purchase
from alogram_payrisk._generated.payrisk_v1.models.purchase_initiator_enum import PurchaseInitiatorEnum
from alogram_payrisk._generated.payrisk_v1.models.purchase_sequence_enum import PurchaseSequenceEnum
from alogram_payrisk._generated.payrisk_v1.models.purchase_usage_enum import PurchaseUsageEnum
from alogram_payrisk._generated.payrisk_v1.models.realtime import Realtime
from alogram_payrisk._generated.payrisk_v1.models.reason_detail import ReasonDetail
from alogram_payrisk._generated.payrisk_v1.models.risk_breakdown import RiskBreakdown
from alogram_payrisk._generated.payrisk_v1.models.risk_category_enum import RiskCategoryEnum
from alogram_payrisk._generated.payrisk_v1.models.risk_level_enum import RiskLevelEnum
from alogram_payrisk._generated.payrisk_v1.models.sca_method_enum import ScaMethodEnum
from alogram_payrisk._generated.payrisk_v1.models.score_record import ScoreRecord
from alogram_payrisk._generated.payrisk_v1.models.scores_success_response import ScoresSuccessResponse
from alogram_payrisk._generated.payrisk_v1.models.signals_account_variant import SignalsAccountVariant
from alogram_payrisk._generated.payrisk_v1.models.signals_interaction_variant import SignalsInteractionVariant
from alogram_payrisk._generated.payrisk_v1.models.signals_request import SignalsRequest
from alogram_payrisk._generated.payrisk_v1.models.stored_credential_context import StoredCredentialContext
from alogram_payrisk._generated.payrisk_v1.models.three_ds_data import ThreeDSData
from alogram_payrisk._generated.payrisk_v1.models.wallet import Wallet

""",
            name=__name__,
            doc=__doc__,
        )
    )
