# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6-rc.3
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from alogram_payrisk._generated.payrisk_v1.models.account import Account
from alogram_payrisk._generated.payrisk_v1.models.entity_ids import EntityIds
from alogram_payrisk._generated.payrisk_v1.models.interaction import Interaction
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class AccountCheckRequest(BaseModel):
    """
    AccountCheckRequest
    """  # noqa: E501

    event_subtype: StrictStr = Field(
        description="The specific subtype of the account event (e.g., 'signup', 'login').",
        alias="eventSubtype",
    )
    entities: Optional[EntityIds] = None
    account: Optional[Account] = None
    interaction: Optional[Interaction] = None
    __properties: ClassVar[List[str]] = [
        "eventSubtype",
        "entities",
        "account",
        "interaction",
    ]

    @field_validator("event_subtype")
    def event_subtype_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            ["signup", "login", "password_reset", "mfa_reset", "setting_change"]
        ):
            raise ValueError(
                "must be one of enum values ('signup', 'login', 'password_reset', 'mfa_reset', 'setting_change')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountCheckRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of entities
        if self.entities:
            _dict["entities"] = self.entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict["account"] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interaction
        if self.interaction:
            _dict["interaction"] = self.interaction.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountCheckRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in AccountCheckRequest) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "eventSubtype": obj.get("eventSubtype"),
                "entities": (
                    EntityIds.from_dict(obj["entities"])
                    if obj.get("entities") is not None
                    else None
                ),
                "account": (
                    Account.from_dict(obj["account"])
                    if obj.get("account") is not None
                    else None
                ),
                "interaction": (
                    Interaction.from_dict(obj["interaction"])
                    if obj.get("interaction") is not None
                    else None
                ),
            }
        )
        return _obj
