# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.10
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from payrisk_v1.models.account import Account
from payrisk_v1.models.entity_ids import EntityIds
from payrisk_v1.models.interaction import Interaction
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class AccountCheckRequest(BaseModel):
    """
    AccountCheckRequest
    """  # noqa: E501

    event_subtype: StrictStr = Field(
        description="The specific subtype of the account event (e.g., 'signup', 'login').",
        alias="eventSubtype",
    )
    entities: Optional[EntityIds] = None
    account: Optional[Account] = None
    interaction: Optional[Interaction] = None
    __properties: ClassVar[List[str]] = [
        "eventSubtype",
        "entities",
        "account",
        "interaction",
    ]

    @field_validator("event_subtype")
    def event_subtype_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            ["signup", "login", "password_reset", "mfa_reset", "setting_change"]
        ):
            raise ValueError(
                "must be one of enum values ('signup', 'login', 'password_reset', 'mfa_reset', 'setting_change')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountCheckRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of entities
        if self.entities:
            _dict["entities"] = self.entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict["account"] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interaction
        if self.interaction:
            _dict["interaction"] = self.interaction.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountCheckRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in AccountCheckRequest) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "eventSubtype": obj.get("eventSubtype"),
                "entities": (
                    EntityIds.from_dict(obj["entities"])
                    if obj.get("entities") is not None
                    else None
                ),
                "account": (
                    Account.from_dict(obj["account"])
                    if obj.get("account") is not None
                    else None
                ),
                "interaction": (
                    Interaction.from_dict(obj["interaction"])
                    if obj.get("interaction") is not None
                    else None
                ),
            }
        )
        return _obj
