# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from payrisk_v1.models.avs_result_enum import AvsResultEnum
from payrisk_v1.models.card_network_enum import CardNetworkEnum
from payrisk_v1.models.cvv_result_enum import CvvResultEnum
from payrisk_v1.models.payment_card_type_enum import PaymentCardTypeEnum
from payrisk_v1.models.sca_method_enum import ScaMethodEnum
from payrisk_v1.models.three_ds_data import ThreeDSData
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Annotated, Self


class Card(BaseModel):
    """
    Card attributes (network, BIN/IIN, issuer country, AVS/CVV, SCA, optional 3DS).
    """  # noqa: E501

    type: StrictStr = Field(description="Fixed to `card` for this schema.")
    card_network: Optional[CardNetworkEnum] = Field(default=None, alias="cardNetwork")
    card_type: Optional[PaymentCardTypeEnum] = Field(default=None, alias="cardType")
    bin: Optional[Annotated[str, Field(min_length=6, strict=True, max_length=8)]] = (
        Field(
            default=None,
            description="Bank Identification Number (IIN). First 6-8 digits of the PAN; do not send full PAN.",
        )
    )
    issuer_country: Optional[
        Annotated[str, Field(min_length=2, strict=True, max_length=2)]
    ] = Field(
        default=None,
        description="ISO 3166-1 alpha-2 country code.",
        alias="issuerCountry",
    )
    avs_result: Optional[AvsResultEnum] = Field(default=None, alias="avsResult")
    cvv_result: Optional[CvvResultEnum] = Field(default=None, alias="cvvResult")
    sca_method: Optional[ScaMethodEnum] = Field(default=None, alias="scaMethod")
    three_ds: Optional[ThreeDSData] = Field(default=None, alias="threeDS")
    __properties: ClassVar[List[str]] = [
        "type",
        "cardNetwork",
        "cardType",
        "bin",
        "issuerCountry",
        "avsResult",
        "cvvResult",
        "scaMethod",
        "threeDS",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["card"]):
            raise ValueError("must be one of enum values ('card')")
        return value

    @field_validator("bin")
    def bin_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-9]{6,8}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{6,8}$/")
        return value

    @field_validator("issuer_country")
    def issuer_country_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Card from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of three_ds
        if self.three_ds:
            _dict["threeDS"] = self.three_ds.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Card from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in Card) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "type": obj.get("type"),
                "cardNetwork": obj.get("cardNetwork"),
                "cardType": obj.get("cardType"),
                "bin": obj.get("bin"),
                "issuerCountry": obj.get("issuerCountry"),
                "avsResult": obj.get("avsResult"),
                "cvvResult": obj.get("cvvResult"),
                "scaMethod": obj.get("scaMethod"),
                "threeDS": (
                    ThreeDSData.from_dict(obj["threeDS"])
                    if obj.get("threeDS") is not None
                    else None
                ),
            }
        )
        return _obj
