# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6-rc.3
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ChannelEnum(str, Enum):
    """
    pos: 'Point of Sale', ecom: 'E-commerce', in_app: 'In-App Purchase', ivr: 'Interactive Voice Response'.
    """

    """
    allowed enum values
    """
    POS = "pos"
    ECOM = "ecom"
    IN_APP = "in_app"
    IVR = "ivr"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChannelEnum from a JSON string"""
        return cls(json.loads(json_str))
