# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency.

The version of the OpenAPI document: 0.2.8
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from alogram_payrisk._generated.payrisk_v1.models.entity_ids import EntityIds
from alogram_payrisk._generated.payrisk_v1.models.external_assessment import ExternalAssessment
from alogram_payrisk._generated.payrisk_v1.models.identity import Identity
from alogram_payrisk._generated.payrisk_v1.models.purchase import Purchase
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Annotated, Self


class CheckRequest(BaseModel):
    """
    Request for synchronous purchase risk check.
    """  # noqa: E501

    event_type: Optional[StrictStr] = Field(
        default="purchase",
        description="(optional) event being checked, this may expand later beyond 'purchase'.",
        alias="eventType",
    )
    payment_intent_id: Optional[
        Annotated[str, Field(min_length=35, strict=True, max_length=35)]
    ] = Field(
        default=None,
        description="Server-minted unique payment identifier.",
        alias="paymentIntentId",
    )
    entities: EntityIds
    purchase: Purchase
    identity: Optional[Identity] = None
    external_assessments: Optional[List[ExternalAssessment]] = Field(
        default=None,
        description="Optional 3rd party risk assessments (e.g. Shopify, Stripe, Signifyd).",
        alias="externalAssessments",
    )
    __properties: ClassVar[List[str]] = [
        "eventType",
        "paymentIntentId",
        "entities",
        "purchase",
        "identity",
        "externalAssessments",
    ]

    @field_validator("event_type")
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["purchase"]):
            raise ValueError("must be one of enum values ('purchase')")
        return value

    @field_validator("payment_intent_id")
    def payment_intent_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^pi_[a-f0-9]{32}$", value):
            raise ValueError(
                r"must validate the regular expression /^pi_[a-f0-9]{32}$/"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of entities
        if self.entities:
            _dict["entities"] = self.entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of purchase
        if self.purchase:
            _dict["purchase"] = self.purchase.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identity
        if self.identity:
            _dict["identity"] = self.identity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in external_assessments (list)
        _items = []
        if self.external_assessments:
            for _item_external_assessments in self.external_assessments:
                if _item_external_assessments:
                    _items.append(_item_external_assessments.to_dict())
            _dict["externalAssessments"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in CheckRequest) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "eventType": (
                    obj.get("eventType")
                    if obj.get("eventType") is not None
                    else "purchase"
                ),
                "paymentIntentId": obj.get("paymentIntentId"),
                "entities": (
                    EntityIds.from_dict(obj["entities"])
                    if obj.get("entities") is not None
                    else None
                ),
                "purchase": (
                    Purchase.from_dict(obj["purchase"])
                    if obj.get("purchase") is not None
                    else None
                ),
                "identity": (
                    Identity.from_dict(obj["identity"])
                    if obj.get("identity") is not None
                    else None
                ),
                "externalAssessments": (
                    [
                        ExternalAssessment.from_dict(_item)
                        for _item in obj["externalAssessments"]
                    ]
                    if obj.get("externalAssessments") is not None
                    else None
                ),
            }
        )
        return _obj
