# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.3.3
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from payrisk_v1.models.decision_resolution_request_analyst import \
    DecisionResolutionRequestAnalyst
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class DecisionResolutionRequest(BaseModel):
    """
    DecisionResolutionRequest
    """  # noqa: E501

    target_type: StrictStr = Field(
        description="The business entity type being resolved.", alias="targetType"
    )
    target_id: StrictStr = Field(
        description="The unique identifier of the target entity under review (e.g. pi_*).",
        alias="targetId",
    )
    decision: StrictStr = Field(
        description="The resolution action to apply to the target."
    )
    analyst: DecisionResolutionRequestAnalyst
    resolution_reason: StrictStr = Field(
        description="The ML-feedback ground-truth reason classification.",
        alias="resolutionReason",
    )
    notes: Optional[StrictStr] = Field(
        default=None,
        description="Additional operational notes or reasoning for this resolution.",
    )
    __properties: ClassVar[List[str]] = [
        "targetType",
        "targetId",
        "decision",
        "analyst",
        "resolutionReason",
        "notes",
    ]

    @field_validator("target_type")
    def target_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["payment_intent", "account_event", "agent_delegation"]):
            raise ValueError(
                "must be one of enum values ('payment_intent', 'account_event', 'agent_delegation')"
            )
        return value

    @field_validator("decision")
    def decision_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["approve", "block", "challenge", "escalate"]):
            raise ValueError(
                "must be one of enum values ('approve', 'block', 'challenge', 'escalate')"
            )
        return value

    @field_validator("resolution_reason")
    def resolution_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "legit_human",
                "legit_agent_authorized",
                "unauthorized_agent",
                "card_testing",
                "account_takeover",
                "friendly_fraud",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('legit_human', 'legit_agent_authorized', 'unauthorized_agent', 'card_testing', 'account_takeover', 'friendly_fraud')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecisionResolutionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of analyst
        if self.analyst:
            _dict["analyst"] = self.analyst.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecisionResolutionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in DecisionResolutionRequest) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "targetType": obj.get("targetType"),
                "targetId": obj.get("targetId"),
                "decision": obj.get("decision"),
                "analyst": (
                    DecisionResolutionRequestAnalyst.from_dict(obj["analyst"])
                    if obj.get("analyst") is not None
                    else None
                ),
                "resolutionReason": obj.get("resolutionReason"),
                "notes": obj.get("notes"),
            }
        )
        return _obj
