# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from payrisk_v1.models.fraud_score import FraudScore
from payrisk_v1.models.reason_detail import ReasonDetail
from payrisk_v1.models.risk_breakdown import RiskBreakdown
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Annotated, Self


class DecisionResponse(BaseModel):
    """
    The synchronous risk decision for a purchase.
    """  # noqa: E501

    assessment_id: Annotated[str, Field(min_length=8, strict=True, max_length=64)] = (
        Field(
            description="Universal decision identifier. For purchases, equals paymentIntentId.",
            alias="assessmentId",
        )
    )
    decision: StrictStr
    decision_at: Annotated[str, Field(strict=True)] = Field(
        description="RFC 3339 timestamp with timezone.", alias="decisionAt"
    )
    risk_score: Union[
        Annotated[float, Field(le=1.0, strict=True, ge=0.0)],
        Annotated[int, Field(le=1, strict=True, ge=0)],
    ] = Field(
        description="DEPRECATED: Use decisionScore instead. Current blended risk score.",
        alias="riskScore",
    )
    decision_score: Union[
        Annotated[float, Field(le=1.0, strict=True, ge=0.0)],
        Annotated[int, Field(le=1, strict=True, ge=0)],
    ] = Field(
        description="The authoritative blended risk score (0.0 - 1.0) derived from expert fusion.",
        alias="decisionScore",
    )
    fraud_score: Optional[FraudScore] = Field(default=None, alias="fraudScore")
    breakdown: Optional[RiskBreakdown] = None
    reason_codes: Optional[List[StrictStr]] = Field(
        default=None,
        description="Technical reason codes for the decision.",
        alias="reasonCodes",
    )
    reasons: Optional[List[ReasonDetail]] = Field(
        default=None, description="Structured reason details for the decision."
    )
    actions: Optional[List[StrictStr]] = None
    payment_intent_id: Optional[
        Annotated[str, Field(min_length=35, strict=True, max_length=35)]
    ] = Field(
        default=None,
        description="Server-minted unique payment identifier.",
        alias="paymentIntentId",
    )
    policy_version: Optional[StrictStr] = Field(
        default=None,
        description="The version of the policy that generated the decision.",
        alias="policyVersion",
    )
    model_version: Optional[StrictStr] = Field(
        default=None,
        description="The version of the model that generated the decision.",
        alias="modelVersion",
    )
    ttl_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(
        default=None,
        description="Time to live for the decision in seconds.",
        alias="ttlSeconds",
    )
    __properties: ClassVar[List[str]] = [
        "assessmentId",
        "decision",
        "decisionAt",
        "riskScore",
        "decisionScore",
        "fraudScore",
        "breakdown",
        "reasonCodes",
        "reasons",
        "actions",
        "paymentIntentId",
        "policyVersion",
        "modelVersion",
        "ttlSeconds",
    ]

    @field_validator("assessment_id")
    def assessment_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9\-_]+$", value):
            raise ValueError(
                r"must validate the regular expression /^[a-zA-Z0-9\-_]+$/"
            )
        return value

    @field_validator("decision")
    def decision_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["approve", "review", "decline", "step_up"]):
            raise ValueError(
                "must be one of enum values ('approve', 'review', 'decline', 'step_up')"
            )
        return value

    @field_validator("decision_at")
    def decision_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(
            r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/"
            )
        return value

    @field_validator("actions")
    def actions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(
                ["step_up", "throttle", "lock_account", "decline", "queue_review"]
            ):
                raise ValueError(
                    "each list item must be one of ('step_up', 'throttle', 'lock_account', 'decline', 'queue_review')"
                )
        return value

    @field_validator("payment_intent_id")
    def payment_intent_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^pi_[a-f0-9]{32}$", value):
            raise ValueError(
                r"must validate the regular expression /^pi_[a-f0-9]{32}$/"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecisionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fraud_score
        if self.fraud_score:
            _dict["fraudScore"] = self.fraud_score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of breakdown
        if self.breakdown:
            _dict["breakdown"] = self.breakdown.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reasons (list)
        _items = []
        if self.reasons:
            for _item_reasons in self.reasons:
                if _item_reasons:
                    _items.append(_item_reasons.to_dict())
            _dict["reasons"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecisionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in DecisionResponse) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "assessmentId": obj.get("assessmentId"),
                "decision": obj.get("decision"),
                "decisionAt": obj.get("decisionAt"),
                "riskScore": obj.get("riskScore"),
                "decisionScore": obj.get("decisionScore"),
                "fraudScore": (
                    FraudScore.from_dict(obj["fraudScore"])
                    if obj.get("fraudScore") is not None
                    else None
                ),
                "breakdown": (
                    RiskBreakdown.from_dict(obj["breakdown"])
                    if obj.get("breakdown") is not None
                    else None
                ),
                "reasonCodes": obj.get("reasonCodes"),
                "reasons": (
                    [ReasonDetail.from_dict(_item) for _item in obj["reasons"]]
                    if obj.get("reasons") is not None
                    else None
                ),
                "actions": obj.get("actions"),
                "paymentIntentId": obj.get("paymentIntentId"),
                "policyVersion": obj.get("policyVersion"),
                "modelVersion": obj.get("modelVersion"),
                "ttlSeconds": obj.get("ttlSeconds"),
            }
        )
        return _obj
