# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.10
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from payrisk_v1.models.risk_level_enum import RiskLevelEnum
from pydantic import (BaseModel, ConfigDict, Field, StrictFloat, StrictInt,
                      StrictStr)
from typing_extensions import Annotated, Self


class ExternalAssessment(BaseModel):
    """
    ExternalAssessment
    """  # noqa: E501

    source: StrictStr = Field(
        description="The provider of the assessment (e.g., 'shopify', 'signifyd')."
    )
    level: RiskLevelEnum
    score: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="The raw score provided by the 3rd party (if applicable).",
    )
    recommendation: Optional[StrictStr] = Field(
        default=None, description="The specific action recommended by the 3rd party."
    )
    reason_codes: Optional[List[StrictStr]] = Field(
        default=None,
        description="Raw reason codes provided by the 3rd party vendor.",
        alias="reasonCodes",
    )
    metadata: Optional[Annotated[str, Field(min_length=1, max_length=2048)]] = Field(
        default=None,
        description="Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. ",
    )
    __properties: ClassVar[List[str]] = [
        "source",
        "level",
        "score",
        "recommendation",
        "reasonCodes",
        "metadata",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalAssessment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalAssessment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in ExternalAssessment) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "source": obj.get("source"),
                "level": obj.get("level"),
                "score": obj.get("score"),
                "recommendation": obj.get("recommendation"),
                "reasonCodes": obj.get("reasonCodes"),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
