# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency.

The version of the OpenAPI document: 0.2.8
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from alogram_payrisk._generated.payrisk_v1.models.confidence_enum import ConfidenceEnum
from alogram_payrisk._generated.payrisk_v1.models.risk_level_enum import RiskLevelEnum
from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self


class FraudScore(BaseModel):
    """
    Fraud score for a specific transaction or entity.
    """  # noqa: E501

    risk_level: RiskLevelEnum = Field(alias="riskLevel")
    confidence: Optional[ConfidenceEnum] = None
    score: Optional[
        Union[
            Annotated[float, Field(le=1.0, strict=True, ge=0.0)],
            Annotated[int, Field(le=1, strict=True, ge=0)],
        ]
    ] = Field(default=None, description="Fraud risk score (0.00 - 1.00).")
    explanation: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(
        default=None,
        description="A human-readable explanation of the fraud score, if available.",
    )
    __properties: ClassVar[List[str]] = [
        "riskLevel",
        "confidence",
        "score",
        "explanation",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FraudScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FraudScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in FraudScore) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "riskLevel": obj.get("riskLevel"),
                "confidence": obj.get("confidence"),
                "score": obj.get("score"),
                "explanation": obj.get("explanation"),
            }
        )
        return _obj
