# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from payrisk_v1.models.postal_address import PostalAddress
from pydantic import (BaseModel, ConfigDict, Field, StrictBool, StrictStr,
                      field_validator)
from typing_extensions import Annotated, Self


class Identity(BaseModel):
    """
    Optional raw identity details for the account associated with the purchase. These fields (email, phone, addresses) are used for normalization, hashing, and risk feature extraction (e.g., email/phone/domain scoring, address risk), and are not stored in raw form by Alogram.  When provided, Alogram will derive and/or cross-check: - emailHash / phoneHash / shippingAddressHash / billingAddressHash   in the internal entity model - email/phone/domain risk signals - address consistency and geo-distance checks
    """  # noqa: E501

    email: Optional[
        Annotated[str, Field(min_length=3, strict=True, max_length=320)]
    ] = Field(default=None, description="Email address of the customer.")
    email_domain: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description='Email domain only (no local part). Useful for domain-level risk and allow/deny lists without sending full email PII. Example: "gmail.com", "merchant-example.co.uk" ',
        alias="emailDomain",
    )
    phone: Optional[Annotated[str, Field(min_length=7, strict=True, max_length=20)]] = (
        Field(
            default=None,
            description='Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: "+1 (415) 555-2671", "415-555-2671", "+14155552671" ',
        )
    )
    shipping_address: Optional[PostalAddress] = Field(
        default=None, alias="shippingAddress"
    )
    billing_address: Optional[PostalAddress] = Field(
        default=None, alias="billingAddress"
    )
    is_bot: Optional[StrictBool] = Field(
        default=None,
        description="Optional: Set to true if client-side bot detection (e.g. reCAPTCHA) triggered.",
        alias="isBot",
    )
    email_reputation: Optional[StrictStr] = Field(
        default=None,
        description="Optional: Client-side assessment of email reputation.",
        alias="emailReputation",
    )
    __properties: ClassVar[List[str]] = [
        "email",
        "emailDomain",
        "phone",
        "shippingAddress",
        "billingAddress",
        "isBot",
        "emailReputation",
    ]

    @field_validator("email")
    def email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$", value):
            raise ValueError(
                r"must validate the regular expression /^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/"
            )
        return value

    @field_validator("email_domain")
    def email_domain_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", value):
            raise ValueError(
                r"must validate the regular expression /^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/"
            )
        return value

    @field_validator("phone")
    def phone_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\+?[1-9][0-9 .\-()]{6,14}[0-9]$", value):
            raise ValueError(
                r"must validate the regular expression /^\+?[1-9][0-9 .\-()]{6,14}[0-9]$/"
            )
        return value

    @field_validator("email_reputation")
    def email_reputation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high"]):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Identity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of shipping_address
        if self.shipping_address:
            _dict["shippingAddress"] = self.shipping_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing_address
        if self.billing_address:
            _dict["billingAddress"] = self.billing_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Identity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in Identity) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "email": obj.get("email"),
                "emailDomain": obj.get("emailDomain"),
                "phone": obj.get("phone"),
                "shippingAddress": (
                    PostalAddress.from_dict(obj["shippingAddress"])
                    if obj.get("shippingAddress") is not None
                    else None
                ),
                "billingAddress": (
                    PostalAddress.from_dict(obj["billingAddress"])
                    if obj.get("billingAddress") is not None
                    else None
                ),
                "isBot": obj.get("isBot"),
                "emailReputation": obj.get("emailReputation"),
            }
        )
        return _obj
