# coding: utf-8

"""
    Payments Risk API

    API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

    The version of the OpenAPI document: 0.1.6-rc.3
    Contact: support@alogram.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from alogram_payrisk._generated.payrisk_v1.models.postal_address import PostalAddress
from typing import Optional, Set
from typing_extensions import Self

class Identity(BaseModel):
    """
    Optional raw identity details for the account associated with the purchase. These fields (email, phone, addresses) are used for normalization, hashing, and risk feature extraction (e.g., email/phone/domain scoring, address risk), and are not stored in raw form by Alogram.  When provided, Alogram will derive and/or cross-check: - emailHash / phoneHash / shippingAddressHash / billingAddressHash   in the internal entity model - email/phone/domain risk signals - address consistency and geo-distance checks 
    """ # noqa: E501
    email: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=320)]] = Field(default=None, description="Email address of the customer.")
    email_domain: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Email domain only (no local part). Useful for domain-level risk and allow/deny lists without sending full email PII. Example: \"gmail.com\", \"merchant-example.co.uk\" ", alias="emailDomain")
    phone: Optional[Annotated[str, Field(min_length=7, strict=True, max_length=20)]] = Field(default=None, description="Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\" ")
    shipping_address: Optional[PostalAddress] = Field(default=None, alias="shippingAddress")
    billing_address: Optional[PostalAddress] = Field(default=None, alias="billingAddress")
    __properties: ClassVar[List[str]] = ["email", "emailDomain", "phone", "shippingAddress", "billingAddress"]

    @field_validator('email')
    def email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/")
        return value

    @field_validator('email_domain')
    def email_domain_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/")
        return value

    @field_validator('phone')
    def phone_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\+?[1-9][0-9 .\-()]{6,14}[0-9]$", value):
            raise ValueError(r"must validate the regular expression /^\+?[1-9][0-9 .\-()]{6,14}[0-9]$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Identity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of shipping_address
        if self.shipping_address:
            _dict['shippingAddress'] = self.shipping_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing_address
        if self.billing_address:
            _dict['billingAddress'] = self.billing_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Identity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in Identity) in the input: " + _key)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "emailDomain": obj.get("emailDomain"),
            "phone": obj.get("phone"),
            "shippingAddress": PostalAddress.from_dict(obj["shippingAddress"]) if obj.get("shippingAddress") is not None else None,
            "billingAddress": PostalAddress.from_dict(obj["billingAddress"]) if obj.get("billingAddress") is not None else None
        })
        return _obj


