# This file is auto-generated. Do not modify manually.
# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency.

The version of the OpenAPI document: 0.2.8
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class InteractionTypeEnum(str, Enum):
    """
    The type of interaction being recorded.
    """

    """
    allowed enum values
    """
    LOGIN = "login"
    FEATURE_USE = "feature_use"
    SETTING_CHANGE = "setting_change"
    PAGE_VIEW = "page_view"
    ENUM_3RD_PARTY_EVENT = "3rd_party_event"
    CUSTOM_EVENT = "custom_event"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InteractionTypeEnum from a JSON string"""
        return cls(json.loads(json_str))
