# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class Integrity(BaseModel):
    """
    Integrity
    """  # noqa: E501

    is_proxy_vpn_tor: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the IP address is associated with a proxy, VPN, or Tor exit node. ",
        alias="isProxyVpnTor",
    )
    is_hosting_provider: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the IP address belongs to a hosting provider (e.g., data center, cloud provider). ",
        alias="isHostingProvider",
    )
    is_headless: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the browser is running in headless mode (e.g., automated testing, scraping). ",
        alias="isHeadless",
    )
    is_automation: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the request originated from an automated script or bot. ",
        alias="isAutomation",
    )
    is_emulator: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the request originated from an emulator (e.g., Android Emulator, iOS Simulator). ",
        alias="isEmulator",
    )
    is_rooted_jailbroken: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the device is rooted (Android) or jailbroken (iOS). ",
        alias="isRootedJailbroken",
    )
    __properties: ClassVar[List[str]] = [
        "isProxyVpnTor",
        "isHostingProvider",
        "isHeadless",
        "isAutomation",
        "isEmulator",
        "isRootedJailbroken",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Integrity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Integrity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in Integrity) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "isProxyVpnTor": obj.get("isProxyVpnTor"),
                "isHostingProvider": obj.get("isHostingProvider"),
                "isHeadless": obj.get("isHeadless"),
                "isAutomation": obj.get("isAutomation"),
                "isEmulator": obj.get("isEmulator"),
                "isRootedJailbroken": obj.get("isRootedJailbroken"),
            }
        )
        return _obj
