# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InteractionTypeEnum(str, Enum):
    """
    The type of interaction being recorded.
    """

    """
    allowed enum values
    """
    LOGIN = "login"
    FEATURE_USE = "feature_use"
    SETTING_CHANGE = "setting_change"
    PAGE_VIEW = "page_view"
    ENUM_3RD_PARTY_EVENT = "3rd_party_event"
    CUSTOM_EVENT = "custom_event"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InteractionTypeEnum from a JSON string"""
        return cls(json.loads(json_str))
