# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class IpInfo(BaseModel):
    """
    IpInfo
    """  # noqa: E501

    ip_address: Optional[
        Annotated[str, Field(min_length=7, strict=True, max_length=15)]
    ] = Field(
        default=None,
        description="IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255. ",
        alias="ipAddress",
    )
    ipv6: Optional[StrictStr] = Field(default=None, description="IPv6 address.")
    ip_version: Optional[StrictStr] = Field(
        default="ipv4", description="IP protocol version.", alias="ipVersion"
    )
    ip_prefix: Optional[StrictStr] = Field(
        default=None,
        description="CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48",
        alias="ipPrefix",
    )
    asn: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None, description="Autonomous System Number (ASN) of the IP address."
    )
    org: Optional[StrictStr] = Field(
        default=None, description="Organization associated with the IP address."
    )
    company: Optional[StrictStr] = Field(
        default=None, description="Company associated with the IP address."
    )
    country: Optional[
        Annotated[str, Field(min_length=2, strict=True, max_length=2)]
    ] = Field(default=None, description="ISO 3166-1 alpha-2 country code.")
    region: Optional[
        Annotated[str, Field(min_length=2, strict=True, max_length=60)]
    ] = Field(default=None, description="Region associated with the IP address.")
    city: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=60)]] = (
        Field(default=None, description="City associated with the IP address.")
    )
    postal_code: Optional[
        Annotated[str, Field(min_length=2, strict=True, max_length=10)]
    ] = Field(
        default=None,
        description="Postal code associated with the IP address.",
        alias="postalCode",
    )
    __properties: ClassVar[List[str]] = [
        "ipAddress",
        "ipv6",
        "ipVersion",
        "ipPrefix",
        "asn",
        "org",
        "company",
        "country",
        "region",
        "city",
        "postalCode",
    ]

    @field_validator("ip_address")
    def ip_address_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(\d{1,3}\.){3}\d{1,3}$", value):
            raise ValueError(
                r"must validate the regular expression /^(\d{1,3}\.){3}\d{1,3}$/"
            )
        return value

    @field_validator("ip_version")
    def ip_version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["ipv4", "ipv6"]):
            raise ValueError("must be one of enum values ('ipv4', 'ipv6')")
        return value

    @field_validator("asn")
    def asn_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^AS\d+$", value):
            raise ValueError(r"must validate the regular expression /^AS\d+$/")
        return value

    @field_validator("country")
    def country_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IpInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IpInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in IpInfo) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "ipAddress": obj.get("ipAddress"),
                "ipv6": obj.get("ipv6"),
                "ipVersion": (
                    obj.get("ipVersion") if obj.get("ipVersion") is not None else "ipv4"
                ),
                "ipPrefix": obj.get("ipPrefix"),
                "asn": obj.get("asn"),
                "org": obj.get("org"),
                "company": obj.get("company"),
                "country": obj.get("country"),
                "region": obj.get("region"),
                "city": obj.get("city"),
                "postalCode": obj.get("postalCode"),
            }
        )
        return _obj
