# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class KycPayload(BaseModel):
    """
    KYC provider result payload.
    """  # noqa: E501

    provider: Optional[StrictStr] = None
    document_type: Optional[StrictStr] = Field(
        default=None,
        description="The document type used for verification.",
        alias="documentType",
    )
    country: Optional[
        Annotated[str, Field(min_length=2, strict=True, max_length=2)]
    ] = None
    result: Optional[StrictStr] = Field(
        default=None, description="The result of the KYC check."
    )
    reason_codes: Optional[List[StrictStr]] = Field(
        default=None,
        description="Array of reason codes for the KYC check.",
        alias="reasonCodes",
    )
    metadata: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=2048)]
    ] = Field(
        default=None,
        description="Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. ",
    )
    __properties: ClassVar[List[str]] = [
        "provider",
        "documentType",
        "country",
        "result",
        "reasonCodes",
        "metadata",
    ]

    @field_validator("document_type")
    def document_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["passport", "national_id", "driver_license", "other"]):
            raise ValueError(
                "must be one of enum values ('passport', 'national_id', 'driver_license', 'other')"
            )
        return value

    @field_validator("result")
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["passed", "failed", "review", "timeout", "error"]):
            raise ValueError(
                "must be one of enum values ('passed', 'failed', 'review', 'timeout', 'error')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KycPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KycPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in KycPayload) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "provider": obj.get("provider"),
                "documentType": obj.get("documentType"),
                "country": obj.get("country"),
                "result": obj.get("result"),
                "reasonCodes": obj.get("reasonCodes"),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
