# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
import pprint
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictStr,
    ValidationError,
    field_validator,
)
from typing import Any, List, Optional
from alogram_payrisk._generated.payrisk_v1.models.bank_transfer import BankTransfer
from alogram_payrisk._generated.payrisk_v1.models.card import Card
from alogram_payrisk._generated.payrisk_v1.models.crypto import Crypto
from alogram_payrisk._generated.payrisk_v1.models.invoice import Invoice
from alogram_payrisk._generated.payrisk_v1.models.realtime import Realtime
from alogram_payrisk._generated.payrisk_v1.models.wallet import Wallet
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PAYMENTMETHOD_ONE_OF_SCHEMAS = [
    "BankTransfer",
    "Card",
    "Crypto",
    "Invoice",
    "Realtime",
    "Wallet",
]


class PaymentMethod(BaseModel):
    """
    Union of instrument-specific payment details.
    """

    # data type: Card
    oneof_schema_1_validator: Optional[Card] = None
    # data type: Wallet
    oneof_schema_2_validator: Optional[Wallet] = None
    # data type: Realtime
    oneof_schema_3_validator: Optional[Realtime] = None
    # data type: BankTransfer
    oneof_schema_4_validator: Optional[BankTransfer] = None
    # data type: Crypto
    oneof_schema_5_validator: Optional[Crypto] = None
    # data type: Invoice
    oneof_schema_6_validator: Optional[Invoice] = None
    actual_instance: Optional[
        Union[BankTransfer, Card, Crypto, Invoice, Realtime, Wallet]
    ] = None
    one_of_schemas: Set[str] = {
        "BankTransfer",
        "Card",
        "Crypto",
        "Invoice",
        "Realtime",
        "Wallet",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = PaymentMethod.model_construct()
        error_messages = []
        match = 0
        # validate data type: Card
        if not isinstance(v, Card):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Card`")
        else:
            match += 1
        # validate data type: Wallet
        if not isinstance(v, Wallet):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Wallet`")
        else:
            match += 1
        # validate data type: Realtime
        if not isinstance(v, Realtime):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Realtime`")
        else:
            match += 1
        # validate data type: BankTransfer
        if not isinstance(v, BankTransfer):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `BankTransfer`"
            )
        else:
            match += 1
        # validate data type: Crypto
        if not isinstance(v, Crypto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Crypto`")
        else:
            match += 1
        # validate data type: Invoice
        if not isinstance(v, Invoice):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Invoice`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("type")
        if not _data_type:
            raise ValueError(
                "Failed to lookup data type from the field `type` in the input."
            )

        # check if data type is `BankTransfer`
        if _data_type == "bank_transfer":
            instance.actual_instance = BankTransfer.from_json(json_str)
            return instance

        # check if data type is `Card`
        if _data_type == "card":
            instance.actual_instance = Card.from_json(json_str)
            return instance

        # check if data type is `Crypto`
        if _data_type == "crypto":
            instance.actual_instance = Crypto.from_json(json_str)
            return instance

        # check if data type is `Invoice`
        if _data_type == "invoice":
            instance.actual_instance = Invoice.from_json(json_str)
            return instance

        # check if data type is `Realtime`
        if _data_type == "realtime":
            instance.actual_instance = Realtime.from_json(json_str)
            return instance

        # check if data type is `Wallet`
        if _data_type == "wallet":
            instance.actual_instance = Wallet.from_json(json_str)
            return instance

        # deserialize data into Card
        try:
            instance.actual_instance = Card.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Wallet
        try:
            instance.actual_instance = Wallet.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Realtime
        try:
            instance.actual_instance = Realtime.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BankTransfer
        try:
            instance.actual_instance = BankTransfer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Crypto
        try:
            instance.actual_instance = Crypto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Invoice
        try:
            instance.actual_instance = Invoice.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into PaymentMethod with oneOf schemas: BankTransfer, Card, Crypto, Invoice, Realtime, Wallet. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[Dict[str, Any], BankTransfer, Card, Crypto, Invoice, Realtime, Wallet]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
