# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from alogram_payrisk._generated.payrisk_v1.models.payment_authorization_outcome import PaymentAuthorizationOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_capture_outcome import PaymentCaptureOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_chargeback import PaymentChargeback
from alogram_payrisk._generated.payrisk_v1.models.payment_chargeback_outcome import PaymentChargebackOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_dispute_outcome import PaymentDisputeOutcome
from alogram_payrisk._generated.payrisk_v1.models.payment_refund_outcome import PaymentRefundOutcome
from typing import Optional, Set
from typing_extensions import Self


class PaymentOutcome(BaseModel):
    """
    Payment outcome details. Structured by lifecycle stage for clarity and validation. Stages include authorization, capture, refund, dispute, chargeback, and chargebackOutcome.
    """  # noqa: E501

    authorization: Optional[PaymentAuthorizationOutcome] = None
    capture: Optional[PaymentCaptureOutcome] = None
    refund: Optional[PaymentRefundOutcome] = None
    dispute: Optional[PaymentDisputeOutcome] = None
    chargeback: Optional[PaymentChargeback] = None
    chargeback_outcome: Optional[PaymentChargebackOutcome] = Field(
        default=None, alias="chargebackOutcome"
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "authorization",
        "capture",
        "refund",
        "dispute",
        "chargeback",
        "chargebackOutcome",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentOutcome from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authorization
        if self.authorization:
            _dict["authorization"] = self.authorization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of capture
        if self.capture:
            _dict["capture"] = self.capture.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refund
        if self.refund:
            _dict["refund"] = self.refund.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dispute
        if self.dispute:
            _dict["dispute"] = self.dispute.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chargeback
        if self.chargeback:
            _dict["chargeback"] = self.chargeback.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chargeback_outcome
        if self.chargeback_outcome:
            _dict["chargebackOutcome"] = self.chargeback_outcome.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentOutcome from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "authorization": (
                    PaymentAuthorizationOutcome.from_dict(obj["authorization"])
                    if obj.get("authorization") is not None
                    else None
                ),
                "capture": (
                    PaymentCaptureOutcome.from_dict(obj["capture"])
                    if obj.get("capture") is not None
                    else None
                ),
                "refund": (
                    PaymentRefundOutcome.from_dict(obj["refund"])
                    if obj.get("refund") is not None
                    else None
                ),
                "dispute": (
                    PaymentDisputeOutcome.from_dict(obj["dispute"])
                    if obj.get("dispute") is not None
                    else None
                ),
                "chargeback": (
                    PaymentChargeback.from_dict(obj["chargeback"])
                    if obj.get("chargeback") is not None
                    else None
                ),
                "chargebackOutcome": (
                    PaymentChargebackOutcome.from_dict(obj["chargebackOutcome"])
                    if obj.get("chargebackOutcome") is not None
                    else None
                ),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
