# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.10
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from payrisk_v1.models.payment_authorization_outcome import \
    PaymentAuthorizationOutcome
from payrisk_v1.models.payment_capture_outcome import PaymentCaptureOutcome
from payrisk_v1.models.payment_chargeback import PaymentChargeback
from payrisk_v1.models.payment_chargeback_outcome import \
    PaymentChargebackOutcome
from payrisk_v1.models.payment_dispute_outcome import PaymentDisputeOutcome
from payrisk_v1.models.payment_refund_outcome import PaymentRefundOutcome
from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self


class PaymentOutcome(BaseModel):
    """
    Payment outcome details. Structured by lifecycle stage for clarity and validation. Stages include authorization, capture, refund, dispute, chargeback, and chargebackOutcome.
    """  # noqa: E501

    authorization: Optional[PaymentAuthorizationOutcome] = None
    capture: Optional[PaymentCaptureOutcome] = None
    refund: Optional[PaymentRefundOutcome] = None
    dispute: Optional[PaymentDisputeOutcome] = None
    chargeback: Optional[PaymentChargeback] = None
    chargeback_outcome: Optional[PaymentChargebackOutcome] = Field(
        default=None, alias="chargebackOutcome"
    )
    __properties: ClassVar[List[str]] = [
        "authorization",
        "capture",
        "refund",
        "dispute",
        "chargeback",
        "chargebackOutcome",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentOutcome from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authorization
        if self.authorization:
            _dict["authorization"] = self.authorization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of capture
        if self.capture:
            _dict["capture"] = self.capture.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refund
        if self.refund:
            _dict["refund"] = self.refund.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dispute
        if self.dispute:
            _dict["dispute"] = self.dispute.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chargeback
        if self.chargeback:
            _dict["chargeback"] = self.chargeback.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chargeback_outcome
        if self.chargeback_outcome:
            _dict["chargebackOutcome"] = self.chargeback_outcome.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentOutcome from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in PaymentOutcome) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "authorization": (
                    PaymentAuthorizationOutcome.from_dict(obj["authorization"])
                    if obj.get("authorization") is not None
                    else None
                ),
                "capture": (
                    PaymentCaptureOutcome.from_dict(obj["capture"])
                    if obj.get("capture") is not None
                    else None
                ),
                "refund": (
                    PaymentRefundOutcome.from_dict(obj["refund"])
                    if obj.get("refund") is not None
                    else None
                ),
                "dispute": (
                    PaymentDisputeOutcome.from_dict(obj["dispute"])
                    if obj.get("dispute") is not None
                    else None
                ),
                "chargeback": (
                    PaymentChargeback.from_dict(obj["chargeback"])
                    if obj.get("chargeback") is not None
                    else None
                ),
                "chargebackOutcome": (
                    PaymentChargebackOutcome.from_dict(obj["chargebackOutcome"])
                    if obj.get("chargebackOutcome") is not None
                    else None
                ),
            }
        )
        return _obj
