# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency.

The version of the OpenAPI document: 0.2.8
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from alogram_payrisk._generated.payrisk_v1.models.payment_event_type import PaymentEventType
from alogram_payrisk._generated.payrisk_v1.models.payment_outcome import PaymentOutcome
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing_extensions import Annotated, Self


class PaymentEvent(BaseModel):
    """
    Payment lifecycle event.
    """  # noqa: E501

    payment_intent_id: Annotated[
        str, Field(min_length=35, strict=True, max_length=35)
    ] = Field(
        description="Server-minted unique payment identifier.", alias="paymentIntentId"
    )
    event_type: PaymentEventType = Field(alias="eventType")
    timestamp: Annotated[str, Field(strict=True)] = Field(
        description="RFC 3339 timestamp with timezone."
    )
    amount: Optional[
        Union[
            Annotated[float, Field(le=1.0e7, strict=True, ge=0.01)],
            Annotated[int, Field(le=10000000, strict=True, ge=1)],
        ]
    ] = Field(
        default=None,
        description="Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. ",
    )
    currency: Optional[
        Annotated[str, Field(min_length=3, strict=True, max_length=3)]
    ] = Field(default=None, description="ISO 4217 currency code (e.g., 'USD').")
    outcome: Optional[PaymentOutcome] = None
    metadata: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=2048)]
    ] = Field(
        default=None,
        description="Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. ",
    )
    __properties: ClassVar[List[str]] = [
        "paymentIntentId",
        "eventType",
        "timestamp",
        "amount",
        "currency",
        "outcome",
        "metadata",
    ]

    @field_validator("payment_intent_id")
    def payment_intent_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^pi_[a-f0-9]{32}$", value):
            raise ValueError(
                r"must validate the regular expression /^pi_[a-f0-9]{32}$/"
            )
        return value

    @field_validator("timestamp")
    def timestamp_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(
            r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/"
            )
        return value

    @field_validator("currency")
    def currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z]{3}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{3}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of outcome
        if self.outcome:
            _dict["outcome"] = self.outcome.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in PaymentEvent) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "paymentIntentId": obj.get("paymentIntentId"),
                "eventType": obj.get("eventType"),
                "timestamp": obj.get("timestamp"),
                "amount": obj.get("amount"),
                "currency": obj.get("currency"),
                "outcome": (
                    PaymentOutcome.from_dict(obj["outcome"])
                    if obj.get("outcome") is not None
                    else None
                ),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
