# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class PostalAddress(BaseModel):
    """
    Postal address used for shipping or billing. Raw values are used only for normalization and risk signals; Alogram will not persist raw address fields in long-term storage.
    """  # noqa: E501

    line1: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(
        default=None, description="First line of the street address."
    )
    line2: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(
        default=None,
        description="Second line of the street address (apartment, suite, etc.).",
    )
    city: Optional[Annotated[str, Field(strict=True, max_length=60)]] = Field(
        default=None, description="City or locality."
    )
    region: Optional[Annotated[str, Field(strict=True, max_length=60)]] = Field(
        default=None, description="State, province, or region."
    )
    postal_code: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(
        default=None, description="Postal / ZIP code.", alias="postalCode"
    )
    country: Optional[
        Annotated[str, Field(min_length=2, strict=True, max_length=2)]
    ] = Field(default=None, description="ISO 3166-1 alpha-2 country code.")
    __properties: ClassVar[List[str]] = [
        "line1",
        "line2",
        "city",
        "region",
        "postalCode",
        "country",
    ]

    @field_validator("country")
    def country_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostalAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostalAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in PostalAddress) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "line1": obj.get("line1"),
                "line2": obj.get("line2"),
                "city": obj.get("city"),
                "region": obj.get("region"),
                "postalCode": obj.get("postalCode"),
                "country": obj.get("country"),
            }
        )
        return _obj
