# This file is auto-generated. Do not modify manually.
# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6-rc.3
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class PurchaseInitiatorEnum(str, Enum):
    """
    Who initiated the transaction (CIT vs MIT).
    """

    """
    allowed enum values
    """
    CARDHOLDER = "cardholder"
    MERCHANT = "merchant"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PurchaseInitiatorEnum from a JSON string"""
        return cls(json.loads(json_str))
