# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from payrisk_v1.models.channel_enum import ChannelEnum
from payrisk_v1.models.device_info import DeviceInfo
from payrisk_v1.models.discount_code import DiscountCode
from payrisk_v1.models.entry_method_enum import EntryMethodEnum
from payrisk_v1.models.merchant_context import MerchantContext
from payrisk_v1.models.order_context import OrderContext
from payrisk_v1.models.payer_type_enum import PayerTypeEnum
from payrisk_v1.models.payment_method import PaymentMethod
from payrisk_v1.models.stored_credential_context import StoredCredentialContext
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing_extensions import Annotated, Self


class Purchase(BaseModel):
    """
    Purchase details for fraud checks; core fields are common, instrument specifics live in `paymentMethod`.
    """  # noqa: E501

    location_id: Optional[
        Annotated[str, Field(min_length=3, strict=True, max_length=50)]
    ] = Field(
        default=None,
        description="Unique identifier for the location where the transaction occurred.",
        alias="locationId",
    )
    device_info: Optional[DeviceInfo] = Field(default=None, alias="deviceInfo")
    timestamp: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None, description="RFC 3339 timestamp with timezone."
    )
    transaction_id: Optional[
        Annotated[str, Field(min_length=3, strict=True, max_length=50)]
    ] = Field(
        default=None,
        description="A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens. ",
        alias="transactionId",
    )
    amount: Union[
        Annotated[float, Field(le=1.0e7, strict=True, ge=0.01)],
        Annotated[int, Field(le=10000000, strict=True, ge=1)],
    ] = Field(
        description="Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. "
    )
    currency: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(
        description="ISO 4217 currency code (e.g., 'USD')."
    )
    channel: Optional[ChannelEnum] = None
    entry_method: Optional[EntryMethodEnum] = Field(default=None, alias="entryMethod")
    payment_method: PaymentMethod = Field(alias="paymentMethod")
    order: Optional[OrderContext] = None
    discounts: Optional[List[DiscountCode]] = Field(
        default=None, description="List of discount codes applied to the purchase."
    )
    payer_type: Optional[PayerTypeEnum] = Field(
        default=PayerTypeEnum.CONSUMER, alias="payerType"
    )
    stored_credential: Optional[StoredCredentialContext] = Field(
        default=None, alias="storedCredential"
    )
    merchant: Optional[MerchantContext] = None
    metadata: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=2048)]
    ] = Field(
        default=None,
        description="Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. ",
    )
    __properties: ClassVar[List[str]] = [
        "locationId",
        "deviceInfo",
        "timestamp",
        "transactionId",
        "amount",
        "currency",
        "channel",
        "entryMethod",
        "paymentMethod",
        "order",
        "discounts",
        "payerType",
        "storedCredential",
        "merchant",
        "metadata",
    ]

    @field_validator("location_id")
    def location_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9\-_]{3,50}$", value):
            raise ValueError(
                r"must validate the regular expression /^[a-zA-Z0-9\-_]{3,50}$/"
            )
        return value

    @field_validator("timestamp")
    def timestamp_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(
            r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/"
            )
        return value

    @field_validator("transaction_id")
    def transaction_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9\-_]+$", value):
            raise ValueError(
                r"must validate the regular expression /^[a-zA-Z0-9\-_]+$/"
            )
        return value

    @field_validator("currency")
    def currency_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Z]{3}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{3}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Purchase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of device_info
        if self.device_info:
            _dict["deviceInfo"] = self.device_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_method
        if self.payment_method:
            _dict["paymentMethod"] = self.payment_method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict["order"] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in discounts (list)
        _items = []
        if self.discounts:
            for _item_discounts in self.discounts:
                if _item_discounts:
                    _items.append(_item_discounts.to_dict())
            _dict["discounts"] = _items
        # override the default output from pydantic by calling `to_dict()` of stored_credential
        if self.stored_credential:
            _dict["storedCredential"] = self.stored_credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of merchant
        if self.merchant:
            _dict["merchant"] = self.merchant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Purchase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in Purchase) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "locationId": obj.get("locationId"),
                "deviceInfo": (
                    DeviceInfo.from_dict(obj["deviceInfo"])
                    if obj.get("deviceInfo") is not None
                    else None
                ),
                "timestamp": obj.get("timestamp"),
                "transactionId": obj.get("transactionId"),
                "amount": obj.get("amount"),
                "currency": obj.get("currency"),
                "channel": obj.get("channel"),
                "entryMethod": obj.get("entryMethod"),
                "paymentMethod": (
                    PaymentMethod.from_dict(obj["paymentMethod"])
                    if obj.get("paymentMethod") is not None
                    else None
                ),
                "order": (
                    OrderContext.from_dict(obj["order"])
                    if obj.get("order") is not None
                    else None
                ),
                "discounts": (
                    [DiscountCode.from_dict(_item) for _item in obj["discounts"]]
                    if obj.get("discounts") is not None
                    else None
                ),
                "payerType": (
                    obj.get("payerType")
                    if obj.get("payerType") is not None
                    else PayerTypeEnum.CONSUMER
                ),
                "storedCredential": (
                    StoredCredentialContext.from_dict(obj["storedCredential"])
                    if obj.get("storedCredential") is not None
                    else None
                ),
                "merchant": (
                    MerchantContext.from_dict(obj["merchant"])
                    if obj.get("merchant") is not None
                    else None
                ),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
