# coding: utf-8

"""
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below.

The version of the OpenAPI document: 0.1.6-rc.3
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from alogram_payrisk._generated.payrisk_v1.models.risk_category_enum import RiskCategoryEnum
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class ReasonDetail(BaseModel):
    """
    Merchant-friendly detail for a specific risk reason.
    """  # noqa: E501

    code: StrictStr = Field(
        description="Technical reason code (e.g., GEO_COUNTRY_SANCTIONED)."
    )
    category: RiskCategoryEnum
    display_name: StrictStr = Field(
        description="Merchant-friendly name for the risk reason.", alias="displayName"
    )
    description: Optional[StrictStr] = Field(
        default=None, description="Detailed explanation of the risk signal."
    )
    recommended_action: Optional[StrictStr] = Field(
        default=None,
        description="Suggested action for the merchant to mitigate this specific risk.",
        alias="recommendedAction",
    )
    __properties: ClassVar[List[str]] = [
        "code",
        "category",
        "displayName",
        "description",
        "recommendedAction",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReasonDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReasonDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in ReasonDetail) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "code": obj.get("code"),
                "category": obj.get("category"),
                "displayName": obj.get("displayName"),
                "description": obj.get("description"),
                "recommendedAction": obj.get("recommendedAction"),
            }
        )
        return _obj
