# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency.

The version of the OpenAPI document: 0.2.8
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from alogram_payrisk._generated.payrisk_v1.models.category_signal import CategorySignal
from pydantic import BaseModel, ConfigDict
from typing_extensions import Self


class RiskBreakdown(BaseModel):
    """
    Breakdown of risk signals by business category.
    """  # noqa: E501

    geography: Optional[CategorySignal] = None
    identity: Optional[CategorySignal] = None
    behavior: Optional[CategorySignal] = None
    transaction: Optional[CategorySignal] = None
    network: Optional[CategorySignal] = None
    __properties: ClassVar[List[str]] = [
        "geography",
        "identity",
        "behavior",
        "transaction",
        "network",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskBreakdown from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of geography
        if self.geography:
            _dict["geography"] = self.geography.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identity
        if self.identity:
            _dict["identity"] = self.identity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of behavior
        if self.behavior:
            _dict["behavior"] = self.behavior.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction
        if self.transaction:
            _dict["transaction"] = self.transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network
        if self.network:
            _dict["network"] = self.network.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskBreakdown from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in RiskBreakdown) in the input: "
                    + _key
                )

        _obj = cls.model_validate(
            {
                "geography": (
                    CategorySignal.from_dict(obj["geography"])
                    if obj.get("geography") is not None
                    else None
                ),
                "identity": (
                    CategorySignal.from_dict(obj["identity"])
                    if obj.get("identity") is not None
                    else None
                ),
                "behavior": (
                    CategorySignal.from_dict(obj["behavior"])
                    if obj.get("behavior") is not None
                    else None
                ),
                "transaction": (
                    CategorySignal.from_dict(obj["transaction"])
                    if obj.get("transaction") is not None
                    else None
                ),
                "network": (
                    CategorySignal.from_dict(obj["network"])
                    if obj.get("network") is not None
                    else None
                ),
            }
        )
        return _obj
