# This file is auto-generated. Do not modify manually.
# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency.

The version of the OpenAPI document: 0.2.8
Contact: support@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ScaMethodEnum(str, Enum):
    """
    The method used for Strong Customer Authentication (SCA).
    """

    """
    allowed enum values
    """
    NONE = "none"
    ENUM_3DS_V1 = "3ds_v1"
    ENUM_3DS_V2 = "3ds_v2"
    OTP_SMS = "otp_sms"
    BIOMETRIC = "biometric"
    FIDO2 = "fido2"
    OTHER = "other"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScaMethodEnum from a JSON string"""
        return cls(json.loads(json_str))
