# coding: utf-8

"""
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)**

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import sys
from typing import Any, Dict, List, Optional, Set, Union

from payrisk_v1.models.signals_account_variant import SignalsAccountVariant
from payrisk_v1.models.signals_interaction_variant import \
    SignalsInteractionVariant
from pydantic import (BaseModel, ConfigDict, Field, StrictStr, ValidationError,
                      field_validator)
from typing_extensions import Self

SIGNALSREQUEST_ONE_OF_SCHEMAS = ["SignalsAccountVariant", "SignalsInteractionVariant"]


class SignalsRequest(BaseModel):
    """
    Request for processing application workflow signals. Determined by `signalType`.
    """

    # data type: SignalsAccountVariant
    oneof_schema_1_validator: Optional[SignalsAccountVariant] = None
    # data type: SignalsInteractionVariant
    oneof_schema_2_validator: Optional[SignalsInteractionVariant] = None
    actual_instance: Optional[
        Union[SignalsAccountVariant, SignalsInteractionVariant]
    ] = None
    one_of_schemas: Set[str] = {"SignalsAccountVariant", "SignalsInteractionVariant"}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = SignalsRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: SignalsAccountVariant
        if not isinstance(v, SignalsAccountVariant):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `SignalsAccountVariant`"
            )
        else:
            match += 1
        # validate data type: SignalsInteractionVariant
        if not isinstance(v, SignalsInteractionVariant):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `SignalsInteractionVariant`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in SignalsRequest with oneOf schemas: SignalsAccountVariant, SignalsInteractionVariant. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in SignalsRequest with oneOf schemas: SignalsAccountVariant, SignalsInteractionVariant. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("signalType")
        if not _data_type:
            raise ValueError(
                "Failed to lookup data type from the field `signalType` in the input."
            )

        # check if data type is `SignalsAccountVariant`
        if _data_type == "account":
            instance.actual_instance = SignalsAccountVariant.from_json(json_str)
            return instance

        # check if data type is `SignalsInteractionVariant`
        if _data_type == "interaction":
            instance.actual_instance = SignalsInteractionVariant.from_json(json_str)
            return instance

        # deserialize data into SignalsAccountVariant
        try:
            instance.actual_instance = SignalsAccountVariant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SignalsInteractionVariant
        try:
            instance.actual_instance = SignalsInteractionVariant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into SignalsRequest with oneOf schemas: SignalsAccountVariant, SignalsInteractionVariant. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into SignalsRequest with oneOf schemas: SignalsAccountVariant, SignalsInteractionVariant. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[Dict[str, Any], SignalsAccountVariant, SignalsInteractionVariant]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
